import "./styles.css";
console.log("Js seems to be working!");

const contentDiv = document.getElementById("content")

const firstDiv = document.createElement('div');
firstDiv.setAttribute('class','textDiv');
firstDiv.textContent  = "This is the FIRST textDiv generated by JavaScript!"
contentDiv.appendChild(firstDiv);

import restaurantImage from  "./images/restaurant.jpg";

const image = document.createElement("img");
image.setAttribute('id','imageMain');
image.src = restaurantImage;

contentDiv.appendChild(image);


const secondDiv = document.createElement('div');
secondDiv.setAttribute('class','textDiv');
secondDiv.textContent  = "This is the SECOND textDiv generated by JavaScript!"
contentDiv.appendChild(secondDiv);
